---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      ref: 7.0.1
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      ref: simp6.0.0-2.1.3
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      ref: simp6.0.0-2.4.0
    augeasproviders_puppet:
      repo: https://github.com/simp/augeasproviders_puppet
      ref: simp-2.1.0
    augeasproviders_ssh:
      repo: https://github.com/simp/augeasproviders_ssh
      ref: simp6.0.0-2.5.0
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      ref: simp6.0.0-2.1.0
    compliance_mapper:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      ref: 2.0.1
    concat:
      repo: https://github.com/simp/puppetlabs-concat
      ref: simp6.0.0-2.2.0
    datacat:
      repo: https://github.com/simp/puppet-datacat
      ref: simp6.0.0-0.6.2
    elasticsearch:
      repo: https://github.com/simp/puppet-elasticsearch
      ref: 5.2.0
    simp_elasticsearch:
      repo: https://github.com/simp/pupmod-simp-simp_elasticsearch
      branch: master
    file_concat:
      repo: https://github.com/simp/puppet-lib-file_concat
      ref: simp6.0.0-1.0.1
    haveged:
      repo: https://github.com/simp/puppet-haveged
      ref: 0.4.0
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      ref: 6.0.1
    java:
      repo: https://github.com/simp/puppetlabs-java
      ref: simp-1.6.0-post1
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      ref: 6.0.0
    logstash:
      repo: https://github.com/simp/puppet-logstash
      branch: 5.2.1
    oddjob:
      repo: https://github.com/simp/pupmod-simp-oddjob
      ref: 2.0.0
    pam:
      repo: https://github.com/simp/pupmod-simp-pam
      ref: 6.0.2
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      ref: 6.0.0
    rsync:
      repo: https://github.com/simp/pupmod-simp-rsync
      ref: 6.0.2
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      ref: 7.0.2
    simpcat:
      repo: https://github.com/simp/pupmod-simp-concat
      ref: 6.0.0
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      ref: 3.2.0
    simp_apache:
      repo: https://github.com/simp/pupmod-simp-apache
      ref: 6.0.0
    simp_options: 
      repo: https://github.com/simp/pupmod-simp-simp_options
      ref: 1.0.2
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: simp6.0.0-4.13.1
    stunnel:
      repo: https://github.com/simp/pupmod-simp-stunnel
      ref: 6.0.1
    tcpwrappers:
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
      ref: 6.0.0
    yum:
      repo: https://github.com/voxpupuli/puppet-yum
      ref: v1.0.0
  symlinks:
    simp_logstash: "#{source_dir}"
