---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      ref: 2.4.1
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      ref: 3.0.0
    augeasproviders_puppet:
      repo: https://github.com/simp/augeasproviders_puppet
      ref: 2.1.1
    augeasproviders_ssh:
      repo: https://github.com/simp/augeasproviders_ssh
      ref: 2.5.3
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      ref: 2.2.0
    compliance_mapper: https://github.com/simp/pupmod-simp-compliance_markup
    concat:
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    datacat:
      repo: https://github.com/simp/puppet-datacat
      ref: simp6.0.0-0.6.2
    elasticsearch:
      repo: https://github.com/simp/puppet-elasticsearch
      ref: 5.2.0
    simp_elasticsearch: https://github.com/simp/pupmod-simp-simp_elasticsearch
    file_concat:
      repo: https://github.com/simp/puppet-lib-file_concat
      ref: simp6.0.0-1.0.1
    haveged:
      repo: https://github.com/simp/puppet-haveged
      ref: 0.4.4
    iptables: https://github.com/simp/pupmod-simp-iptables
    java:
      repo: https://github.com/simp/puppetlabs-java
      ref: simp-1.6.0-post1
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    logstash:
      repo: https://github.com/simp/puppet-logstash
      branch: 5.2.1
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    rsync: https://github.com/simp/pupmod-simp-rsync
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simpcat: https://github.com/simp/pupmod-simp-concat
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_apache: https://github.com/simp/pupmod-simp-apache
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: 4.24.0
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    yum:
      repo: https://github.com/simp/voxpupuli-yum
      ref: v2.1.0
  symlinks:
    simp_logstash: "#{source_dir}"
