---
HOSTS:
  server-el7:
    roles:
    - server
    - default
    - master
    - logstash_server
    - el7
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      logstash:
        baseurl: https://artifacts.elastic.co/packages/5.x/yum
        gpgkeys:
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://getfedora.org/static/352C64E5.txt
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  es-el7:
    roles:
    - elasticsearch_server
    - agent
    - el7
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://getfedora.org/static/352C64E5.txt
      elasticsearch:
        baseurl: https://artifacts.elastic.co/packages/5.x/yum
        gpgkeys:
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  server-el6:
    roles:
    - logstash_server
    - el6
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
    yum_repos:
      logstash:
        baseurl: https://artifacts.elastic.co/packages/5.x/yum
        gpgkeys:
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
        gpgkeys:
        - https://getfedora.org/static/0608B895.txt
  es-el6:
    roles:
    - elasticsearch_server
    - agent
    - el6
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
        gpgkeys:
        - https://getfedora.org/static/0608B895.txt
      elasticsearch:
        baseurl: https://artifacts.elastic.co/packages/5.x/yum
        gpgkeys:
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 1024
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
